# Generated by Django 4.2.6 on 2023-11-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commemt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commemt',
            new_name='Comment',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='blog_commen_created_0e6ed4_idx',
            old_name='blog_commem_created_236afa_idx',
        ),
    ]
